name: CI/CD Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permission:
  id-token: write
  pages: write
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:    
      - uses: actions/checkout@v3
      
      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Generate CSV file (antag att det finns ett script för detta)
      - name: Generate CSV file
        run: python generate_csv.py
      
      # Convert CSV to JSON
      - name: Convert CSV to JSON
        run: python csvtojson.py
      
      # Run unit tests
      - name: Run unit tests
        run: python -m unittest discover -s . -p "test_*.py"
      
      # Copy files to dist folder
      - name: Copy to dist
        run: |
          mkdir dist
          cp index.html dist/index.html
          cp data.json dist/data.json
          cp script.js dist/script.js

      # Setup Pages
      - name: Setup Pages
        uses: actions/configure-pages@v2

      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'dist'

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
